name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      
      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}
      
      - name: ZIP files
        run: |
          cd /home/runner/work/onkyo-custom/onkyo-custom/custom_components/onkyo-custom
          zip onkyo-custom.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/onkyo-custom/onkyo-custom/custom_components/onkyo-custom/onkyo-custom.zip
          asset_name: onkyo-custom.zip
          tag: ${{ github.ref }}
          overwrite: true
